// Phase 1 mock data. Shape mirrors what Phase 3 derivations will return
// so the UI does not need to change when real data lands.

import type { MarketSnapshot, Regime } from '../types';

export function getMockSnapshot(): MarketSnapshot {
  const regime: Regime = 'elevated';
  return {
    captured_at: new Date().toISOString(),
    regime,
    regime_score: 42,
    tiles: [
      {
        key: 'vxn',
        label: 'VXN',
        value: '24.3',
        raw: 24.3,
        percentile: 68,
        direction: 'up',
        duration: '3d ↑',
        note: 'CBOE Nasdaq-100 Volatility Index. 30-day implied vol on NDX options, like VIX for tech.',
        description: 'Third consecutive day higher, breaking the 22 floor.',
      },
      {
        key: 'vxn_vix_ratio',
        label: 'VXN / VIX',
        value: '1.18',
        raw: 1.18,
        percentile: 72,
        direction: 'up',
        duration: 'rising',
        note: 'Ratio of Nasdaq vol to S&P vol. Above 1.15 = tech carrying more implied stress than the broad market.',
        description: 'NDX dispersion widening vs SPX — tech-specific stress.',
      },
      {
        key: 'vix_term',
        label: 'VIX Term (M1/M3)',
        value: '0.94',
        raw: 0.94,
        percentile: 80,
        direction: 'up',
        duration: 'flattening',
        note: 'Front / third-month VIX futures ratio. Below 1.0 = inverted curve, market pricing near-term stress above longer-term.',
        description: 'Front-month inverted vs M3 — near-term fear bid.',
      },
      {
        key: 'vvix',
        label: 'VVIX',
        value: '98.2',
        raw: 98.2,
        percentile: 55,
        direction: 'flat',
        note: 'Vol-of-vol. Implied volatility of VIX options. Rising VVIX = demand for tail hedges.',
        description: 'Mid-range, no aggressive tail bidding yet.',
      },
      {
        key: 'qqq_skew_25d',
        label: 'QQQ 25Δ Skew',
        value: '4.1v',
        raw: 4.1,
        percentile: 61,
        direction: 'up',
        duration: '2d ↑',
        note: 'Put IV(25Δ) − Call IV(25Δ) on QQQ, in vol points. Higher skew = more demand for downside protection relative to upside.',
        description: 'Put demand outpacing calls, no flat-skew capitulation yet.',
      },
      {
        key: 'implied_corr',
        label: 'Implied Corr',
        value: '0.61',
        raw: 0.61,
        percentile: 58,
        direction: 'up',
        note: 'Implied correlation across NDX constituents derived from QQQ IV vs weighted single-name IV. Rising = names moving together.',
        description: 'Dispersion compressing — names starting to move in lockstep.',
      },
      {
        key: 'realized_corr',
        label: 'Realized Corr 20d',
        value: '0.48',
        raw: 0.48,
        percentile: 49,
        direction: 'flat',
        note: '20-day trailing pairwise correlation across the watchlist. Leading indicator when rising fast.',
        description: 'Realized still lagging implied — dispersion book holds.',
      },
      {
        key: 'dealer_gamma',
        label: 'Dealer Gamma',
        value: '−$1.2B',
        raw: -1.2,
        percentile: 22,
        direction: 'down',
        duration: 'negative',
        note: 'Estimated net gamma exposure of options dealers ($ per 1pt SPX move). Negative = dealers must sell into declines and buy into rallies, amplifying moves.',
        description: 'Dealers short gamma — flows amplify moves both ways.',
      },
      {
        key: 'equity_pc_5d',
        label: 'Equity P/C (5d)',
        value: '0.72',
        raw: 0.72,
        percentile: 64,
        direction: 'up',
        note: '5-day average equity-only put/call ratio. Rising = retail / hedgers buying more puts than calls.',
        description: 'Put buying firming up, not yet extreme.',
      },
      {
        key: 'hy_oas',
        label: 'HY OAS',
        value: '362bp',
        raw: 362,
        percentile: 44,
        direction: 'up',
        note: 'ICE BofA US High Yield Index option-adjusted spread (BAMLH0A0HYM2). Tightest credit-stress canary — moves before equities in deeper drawdowns.',
        description: 'Widening but contained — credit not confirming equity stress yet.',
      },
      {
        key: 'move_index',
        label: 'MOVE',
        value: '104',
        raw: 104,
        percentile: 51,
        direction: 'flat',
        note: 'ICE BofA MOVE Index — Treasury volatility. The "VIX for bonds". Co-moves with equity vol in macro dislocations.',
        description: 'Treasury vol benign — stress is equity-local for now.',
      },
      {
        key: 'ndx_pct_above_50dma',
        label: 'NDX %>50DMA',
        value: '46%',
        raw: 46,
        percentile: 38,
        direction: 'down',
        note: 'Share of Nasdaq-100 constituents trading above their 50-day moving average. Breadth gauge — low readings signal narrow leadership.',
        description: 'Below half — breadth deteriorating under the surface.',
      },
      {
        key: 'ndx_top10_share',
        label: 'NDX Top10 YTD',
        value: '81%',
        raw: 81,
        percentile: 88,
        direction: 'up',
        note: 'Year-to-date return contribution from the top-10 NDX names. Extreme readings = fragile leadership concentration.',
        description: 'Top-10 carrying 4x their weight — leadership brittle.',
      },
      {
        key: 'nyse_new_highs_lows',
        label: 'NYSE Hi/Lo',
        value: '42 / 88',
        raw: 42 - 88,
        percentile: 28,
        direction: 'down',
        note: 'Daily count of NYSE 52-week new highs vs 52-week new lows. Negative ratio = broad distribution below the surface.',
        description: 'New lows outpacing new highs 2:1 — distribution under the tape.',
      },
      {
        key: 'list_iv_rank',
        label: 'List IV Rk >90',
        value: '3',
        raw: 3,
        percentile: 65,
        direction: 'up',
        duration: '+2 wk',
        note: 'Count of watchlist names with IV-rank above 90 (52-week high IV). Rising = individual names getting re-rated.',
        description: 'Three names at 52w-high IV — single-name stress concentrating.',
      },
      {
        key: 'vix',
        label: 'VIX',
        value: '20.6',
        raw: 20.6,
        percentile: 60,
        direction: 'up',
        note: 'CBOE S&P 500 Volatility Index. 30-day implied vol on SPX. The benchmark fear gauge.',
        description: 'Above 20 — off-the-floor, not yet panic.',
      },
    ],
    sub_signals: {
      vxn_pct: 68,
      term_inversion: 80,
      skew_trend: 61,
      dealer_gamma: 78,
      implied_corr: 58,
      hy_oas: 44,
      breadth: 62,
      list_iv_rank: 65,
    },
  };
}
