// Phase 1 mock data. Shape mirrors what Phase 3 derivations will return
// so the UI does not need to change when real data lands.

import type { MarketSnapshot, Regime } from '../types';

export function getMockSnapshot(): MarketSnapshot {
  const regime: Regime = 'elevated';
  return {
    captured_at: new Date().toISOString(),
    regime,
    regime_score: 42,
    tiles: [
      {
        key: 'vxn',
        label: 'VXN',
        value: '24.3',
        raw: 24.3,
        percentile: 68,
        direction: 'up',
        duration: '3d ↑',
        note: 'Nasdaq-100 implied volatility, 30d',
      },
      {
        key: 'vxn_vix_ratio',
        label: 'VXN / VIX',
        value: '1.18',
        raw: 1.18,
        percentile: 72,
        direction: 'up',
        duration: 'rising',
      },
      {
        key: 'vix_term',
        label: 'VIX Term (M1/M3)',
        value: '0.94',
        raw: 0.94,
        percentile: 80,
        direction: 'up',
        duration: 'flattening',
        note: 'Below 1.0 = inverted front end',
      },
      {
        key: 'vvix',
        label: 'VVIX',
        value: '98.2',
        raw: 98.2,
        percentile: 55,
        direction: 'flat',
      },
      {
        key: 'qqq_skew_25d',
        label: 'QQQ 25Δ Skew',
        value: '4.1v',
        raw: 4.1,
        percentile: 61,
        direction: 'up',
        duration: '2d ↑',
        note: 'Put IV(25Δ) − Call IV(25Δ)',
      },
      {
        key: 'implied_corr',
        label: 'Implied Corr',
        value: '0.61',
        raw: 0.61,
        percentile: 58,
        direction: 'up',
      },
      {
        key: 'realized_corr',
        label: 'Realized Corr 20d',
        value: '0.48',
        raw: 0.48,
        percentile: 49,
        direction: 'flat',
      },
      {
        key: 'dealer_gamma',
        label: 'Dealer Gamma',
        value: '−$1.2B',
        raw: -1.2,
        percentile: 22,
        direction: 'down',
        duration: 'negative',
        note: 'Below zero → dealers short gamma',
      },
      {
        key: 'equity_pc_5d',
        label: 'Equity P/C (5d)',
        value: '0.72',
        raw: 0.72,
        percentile: 64,
        direction: 'up',
      },
      {
        key: 'hy_oas',
        label: 'HY OAS',
        value: '362bp',
        raw: 362,
        percentile: 44,
        direction: 'up',
      },
      {
        key: 'move_index',
        label: 'MOVE',
        value: '104',
        raw: 104,
        percentile: 51,
        direction: 'flat',
      },
      {
        key: 'ndx_pct_above_50dma',
        label: 'NDX %>50DMA',
        value: '46%',
        raw: 46,
        percentile: 38,
        direction: 'down',
      },
      {
        key: 'ndx_top10_share',
        label: 'NDX Top10 YTD',
        value: '81%',
        raw: 81,
        percentile: 88,
        direction: 'up',
        note: 'Leadership concentration',
      },
      {
        key: 'nyse_new_highs_lows',
        label: 'NYSE Hi/Lo',
        value: '42 / 88',
        raw: 42 - 88,
        percentile: 28,
        direction: 'down',
      },
      {
        key: 'list_iv_rank',
        label: 'List IV Rk >90',
        value: '3',
        raw: 3,
        percentile: 65,
        direction: 'up',
        duration: '+2 wk',
      },
      {
        key: 'vix',
        label: 'VIX',
        value: '20.6',
        raw: 20.6,
        percentile: 60,
        direction: 'up',
      },
    ],
    sub_signals: {
      vxn_pct: 68,
      term_inversion: 80,
      skew_trend: 61,
      dealer_gamma: 78,
      implied_corr: 58,
      hy_oas: 44,
      breadth: 62,
      list_iv_rank: 65,
    },
  };
}
